### PR TITLE
feat: add environment to error message

### PR DESCRIPTION
**Pull request by lzap**
I find sometimes difficult to find which Kibana should I start searching for. Error reports usually do not tell.

### CODE REVIEW

**Comment by lzap** [comment]
Also added Edge ID which is also propagated to other services as well (sources and image builder).

Finally, rebased to fix checks and unexported error payload which must be used via the New method to enforce that info from context is present.

**Review by avitova — COMMENTED** [review]
So I tested it, and it looks like everything works fine. I have a minor nitpick. I am not sure if the alias InClowder() is even needed, I found it a bit confusing.

**Comment by lzap** [comment]
Sure, rebased.

**Comment by lzap** [comment]
Good point, so what happened was that I wanted to unexport the ErrorPayload and only have `NewErrorPayload` function to be able to create the type to ensure fields are initialized properly. But that actually removed the type from OpenAPI.

I am fixing that, I guess that is not possible, at least without some ugly hacks like user-defined JSON marshalling.

I am going to merge this since our stage is stuck somehow and I want to know if thats fixed or not.

**Comment by lzap** [comment]
Rebased.

**Comment by adiabramovitch** [comment]
LGTM

**Pull request merged**
