### PR TITLE
Add requestbody to POST /pubkeys

### PR DESCRIPTION
**Pull request by akhil-jha**
Please let me know if I have to add anything anywhere else too!

### CODE REVIEW

**Comment by adiabramovitch** [comment]
@akhil-jha if you are adding an endpoint you should follow the instructions here: 
https://github.com/RHEnVision/provisioning-backend/blob/main/docs/openapi.md

You are missing the change in path.yml, after that run ,make generate-spec and those files will be generated automatically

**Review by ezr-ondrej — APPROVED** [review]
Thanks ! :+1: I believe we should distinguish between request and response, as `id` is not allowed in request, but that's a story for another day ^_^

**Comment by ezr-ondrej** [comment]
Force merging, given the contribution is from QE.... weird it still requires an ack :thinking:

**Comment by akhil-jha** [comment]
@lzap could you rebase #135 ? :)

**Pull request merged**
