### PR TITLE
Add Source ID

### PR DESCRIPTION
**Pull request by avitova**
Please, let me know if we need to change Source ID in updatePubkeyResource. :) I was not sure about that one. Both integration and unit test are passing.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
> Please, let me know if we need to change Source ID in updatePubkeyResource.

Good question, hard to answer, because we are not using that method, so I'm of an opinion we should not have such a method, but given it's there, lets just allow changing everything. I'd argue for deleting it, but thats out of scope :)

**Review by ezr-ondrej — APPROVED** [review]
Needs db drop and remigrate, so I'll wait for everyone to see we are adding this.
@lzap @adiabramovitch @amirfefer can you pls ack? :)

**Comment by lzap** [comment]
I vote for deleting the unused update function. If you can squeeze that in, not a blocker tho.

**Comment by adiabramovitch** [comment]
Sure we just need a follow-up PR for that - to add the assume role part in the handler itself.

**Review by adiabramovitch — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
> I vote for deleting the unused update function

I'll do that in a follow-up to have a discussion over unused functions in general :)

**Pull request merged**
