### PR TITLE
feat: availability check kafka topic

### PR DESCRIPTION
**Pull request by lzap**
This adds the internal topic for the check.

### CODE REVIEW

**Comment by lzap** [comment]
Let me add a log into statuser log output to see if a message is actually being received.

**Comment by lzap** [comment]
According to:

https://github.com/RedHatInsights/platform-mq/blob/master/topics/topics.json

the common prefix is "platform" so rebased to: `platform.provisioning.internal.availability-check`

**Comment by lzap** [comment]
https://github.com/RedHatInsights/platform-mq/pull/250

**Review by ezr-ondrej — APPROVED** [review]
We are ready in stage, so lets do this :tada:

**Pull request merged**
