### PR TITLE
Change golangci version in makefile

### PR DESCRIPTION
**Pull request by adiabramovitch**
Thanks for the contribution, take a moment to read our contributing and security guidelines:

**Checklist**
- [x] https://github.com/RHEnVision/provisioning-backend#contributing
- [x] https://github.com/RedHatInsights/secure-coding-checklist

We are pinning to a specific version because of this https://github.com/golangci/golangci-lint/issues/2851

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Can you please add a comment we are pinning because of a bug: https://github.com/golangci/golangci-lint/issues/2851 ? So we know we can unpin once that's resolved :)

**Comment by lzap** [comment]
I already have that in my other PR: https://github.com/RHEnVision/provisioning-backend/pull/29/commits/4654fbcb6868191e505485392edee9d86d522c40 so whatever is merged first.

**Comment by lzap** [comment]
Yeah drop a comment here and also in the github action YAML if possible (there is also a pinned version for the same reason).

**Review by ezr-ondrej — APPROVED** [review]
Thanks @adiabramovitch ! :+1:

**Pull request merged**
