### PR TITLE
fix(HMS-1259): Add adjustable datasource and SLOs panels

### PR DESCRIPTION
**Pull request by adiabramovitch**
Also added two panels to show the HTTP request latency and Source availability latency according to our SLOs

### CODE REVIEW

**Comment by adiabramovitch** [comment]
> 
 Fixing it, be ready soon

**Comment by adiabramovitch** [comment]
> There are conflicts (?).
> 
> How do I test this? :-)

In order to test it you can copy the JSON itself (from line 12) and paste it instead of the JSON [here](https://grafana.stage.devshift.net/d/22222/provisioning?editview=dashboard_json):

**Review by lzap — APPROVED** [review]
It works. Thanks.

**Comment by ezr-ondrej** [comment]
Did not have time to review, but could we also make the production datasource selected by default? :)

**Comment by lzap** [comment]
I think the production cluster was the default, yes. Now that my Grafana remembered my selection, I cannot confirm.

**Pull request merged**
