### PR TITLE
chore(deps): update dependencies for security

### PR DESCRIPTION
**Pull request by lzap**
Cherry picked this one since it was reported by our security tool.

Others do not update becuse of Go version. So let’s hold on them.

### CODE REVIEW

**Comment by lzap** [comment]
Hmmm. I wrote a tool that allows me to bump ALL versions and keep Go version requirement. Let’s try the tool here:

https://github.com/lzap/gobump

**Comment by lzap** [comment]
Sources in ephemeral is broken it seems.

**Comment by ezr-ondrej** [comment]
/retest

lets see what's up with it

**Comment by ezr-ondrej** [comment]
ah, it got fixed in the meantime :)

**Review by ezr-ondrej — APPROVED** [review]
Azure still broken, but we're testing it again in stage (where the test works :) )

**Pull request merged**
