### PR TITLE
refactor: fix worker metrics registrations

### PR DESCRIPTION
**Pull request by adiabramovitch**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Follow up from #439

**Review by ezr-ondrej — APPROVED** [review]
Thanks @adiabramovitch, FYI @lzap :)

**Comment by lzap** [comment]
Is this just cosmetic change or does this have any effect?

**Comment by adiabramovitch** [comment]
> Is this just cosmetic change or does this have any effect?
cosmetic

**Pull request merged**
