### PR TITLE
fix: throw an error when pubkey is duplicated (HMSPROV-309)

### PR DESCRIPTION
**Pull request by adiabramovitch**

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Thanks, lets merge before someone messes up the DB in our fresh stage environment ^_^

**Comment by lzap** [comment]
Thanks, the code still needs more love as we need to actually check all keys on AWS prior any action, looking it up in our database is unfortunately not enough as users might imported ssh keys manually.

**Comment by adiabramovitch** [comment]
@lzap This is a temporary fix until we will discuss a needed refactoring for the pubkeys

**Comment by ezr-ondrej** [comment]
Yeah, I totaly agree we need to take it further, but for now I prefer failures then inconsistent DB :)

**Pull request merged**
