### PR TITLE
chore: better error when clowder is not present

### PR DESCRIPTION
**Pull request by lzap**
Slightly improves errors, tho I am not sure if these structures are validated (required) or not in clowder.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I thing the error performance team had hit was about the application we depend on not being deployed in the environment (sources, IB or RBAC is missing and thus it's endpoint not filled)

**Comment by ezr-ondrej** [comment]
looks like it's working for the happy path tho :+1:

**Comment by lzap** [comment]
Yeah I realized that too, but I saw we have similar checks in place so thought it might be useful. Probably not.

**Review by ezr-ondrej — APPROVED** [review]
Sure, just in case :shrug: Thanks :+1:

**Pull request merged**
