### PR TITLE
ci(KONFLUX-2339): Update cloud image to konflux

### PR DESCRIPTION
**Pull request by akhil-jha**
Update deploy image to konflux image

### CODE REVIEW

**Comment by skateman** [comment]
@akhil-jha can you please also incorporate this file into the PR? https://github.com/RedHatInsights/compliance-backend/blob/master/renovate.json

**Review by ezr-ondrej — APPROVED** [review]
LGTM :+1:

**Comment by ezr-ondrej** [comment]
Failures are just Azure, which should not be fault of this PR. Merging.

**Pull request merged**
