### PR TITLE
refactor: remove deprecated instance types endpoint

### PR DESCRIPTION
**Pull request by lzap**
SSIA

### CODE REVIEW

**Comment by lzap** [comment]
Next up after this is merged:

```
				// TODO DEPRECATED: replaced with upload_info
				r.Get("/account_identity", s.GetAWSAccountIdentity)
```

**Review by avitova — APPROVED** [review]
Looks like this is all we need to remove! LGTM

**Comment by lzap** [comment]
All green.

**Review by adiabramovitch — APPROVED** [review]

**Comment by adiabramovitch** [comment]
We need ack form QE :)  @akhil-jha

**Comment by lzap** [comment]
Since IQE tests are passing and Akhil might not show up for some time, @mshriver can you confirm that the (long) deprecated endpoint GET `/account_identity` is not used anywhere in the IQE pipeline? Thanks.

**Review by ezr-ondrej — APPROVED** [review]
It's indeed long deprecated, I'll file a MR updating the client with the changes from here, but I guess we can risk it here, this should not be used in any integration tests :)

**Pull request merged**
