### PR TITLE
fix(HMS-2830): Add resource group to Azure response

### PR DESCRIPTION
**Pull request by ezr-ondrej**
We have missed adding Resource Group to the response in b369cf818fa9ea4ef160caec828cec17ae745504.

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Apologies. Merging.

**Comment by lzap** [comment]
_iqe_provisioning_api.exceptions.ApiAttributeError: V1AzureReservationResponse has no attribute 'resource_group' at ['received_data']['resource_group']_

We need to do an IQE refresh, let me learn how to do it.

**Comment by lzap** [comment]
/retest

IQE merged

**Comment by ezr-ondrej** [comment]
/retest

Maybe the new IQE version was not published properly yet :)

**Comment by akhil-jha** [comment]
You'd need a rebase I believe

**Comment by ezr-ondrej** [comment]
> You'd need a rebase I believe

For the new account? I think the pipeline rebases the PR automatically :thinking: let see :)

**Comment by lzap** [comment]
_TypeError: __init__() got an unexpected keyword argument 'resource_group'_

**Review by akhil-jha — APPROVED** [review]

**Pull request merged**
