### PR TITLE
clowdapp: Fix typos

### PR DESCRIPTION
**Pull request by pablomh**
Thanks for the contribution, make sure your commit message follows this subject style:

        type: brief summary up to 70 characters or
        type(scope): brief summary up to 70 characters

Type is required, scope is optional. Prefer lower-case and avoid dot at the end.

Find more info about types and scopes at:

https://github.com/RHEnVision/provisioning-backend#contributing

Take a moment to read our contributing and security guidelines:

https://github.com/RedHatInsights/secure-coding-checklist

**Checklist**

- [x] all commit messages follows the policy above
- [x] the change follows our security guidelines

### CODE REVIEW

**Review by lzap — APPROVED** [review]

**Comment by lzap** [comment]
> Find more info about types and scopes at:
> 
> https://github.com/RHEnVision/provisioning-backend#contributing

Thank you for the contribution, please read ^^

**Comment by pablomh** [comment]
> > Find more info about types and scopes at:
> > https://github.com/RHEnVision/provisioning-backend#contributing
> 
> Thank you for the contribution, please read ^^

Thanks for the pointer. Obviously I hadn't done my homework :/

**Comment by akhil-jha** [comment]
I see the diff doesn't change our app's functioning so I guess it's okay, but in case you plan to change something functionally, you need to be a member in a team (with organisation visibility as public) so the pr_checks are able to get triggered.

**Comment by pablomh** [comment]
Hi Akhil,

Even though I'm tangentially related to the team (as part of the Perf&Scale team responsible for HMS testing) I don't think I should be member of such team, so my intention was to contribute this as if it was part of any "external" contribution. I don't know if it makes any sense :)

**Comment by ezr-ondrej** [comment]
Thanks @pablomh! Great to see ppl contributing 🧡
Congratulations for your first contribution to the repo 🎉

**Pull request merged**
