### PR TITLE
chore: replace scripts with compose

### PR DESCRIPTION
**Pull request by lzap**
SSIA

I have rewritten the main and development setup README as well.

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
I guess it's up to @avitova if she's ready? :)

**Comment by lzap** [comment]
Great chance to validate documentation and do some last minute fixups during your migration :-)

**Comment by ezr-ondrej** [comment]
/retest

Testing the bot :)

**Comment by lzap** [comment]
I don’t think this needs to pass :-) No code changes... @avitova can you review this please?

**Comment by ezr-ondrej** [comment]
> I don’t think this needs to pass :-) No code changes... @avitova can you review this please?

No, it doesn't need to pass here, I just wanted to test the pipeline here as it should pass here for sure IMO :)

**Comment by lzap** [comment]
https://proxy.golang.org has some issues, it works now.

/retest

**Review by avitova — APPROVED** [review]
Finally got my compose setup working. Looks good, thank you. :)

**Comment by ezr-ondrej** [comment]
/retest

cmon, bot! xD

**Comment by ezr-ondrej** [comment]
Thank you @lzap for creating these scripts and seeing the through its full lifecycle and thanks @amirfefer for starting out the next generation and finally @lzap, @adiabramovitch and @avitova for testing it all! :+1:

**Pull request merged**
