### PR TITLE
feat: add provider for Sources in OpenAPI spec

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Refs HMS-969

@adiabramovitch I guess we forgot this?
@akhil-jha do we want to cover this, or is this tiny enough?

### CODE REVIEW

**Review by akhil-jha — APPROVED** [review]
Yeah, tiny enough :) 
If I face any issue, I'll let you know.

**Comment by adiabramovitch** [comment]
@ezr-ondrej Thank you!

**Pull request merged**
