### PR TITLE
chore: update cloudwatchwriter to 1.2.0

### PR DESCRIPTION
**Pull request by lzap**
This brings an important bug fix that was found upstream:

* https://github.com/lzap/cloudwatchwriter2/commit/3eea0d9a1c1d908ab5c128ff9f73214d8abcba2f
* https://github.com/mec07/cloudwatchwriter/commit/39d443b0eeec4bd349108cfdc94edec009bc40b8

This could cause the logger to send to AWS way too often leading to request throttling.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Are there any plans to migrate to an official clowdwatch dependency? Or shall we start maintaining it for other teams as well?

**Comment by akhil-jha** [comment]
Oh wait...you need a rebase first. My bad 🤦 
@lzap ^

**Comment by lzap** [comment]
> an official clowdwatch dependency

What's that?

This is a tiny project (about 200 LOC) I just upgraded it to AWS SDK v2. No other library was on v2.

Tests are green.

**Review by ezr-ondrej — APPROVED** [review]
Thanks :+1:

**Pull request merged**
