### PR TITLE
ci: Change CICD_URL for pr_check

### PR DESCRIPTION
**Pull request by akhil-jha**
Bonfire repository for pr_checks is now legacy. 
cicd-tools repo has the latest changes.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Any reasoning behind it? :thinking: I kinda get it, but would be good to explain in the description for future reference :)

**Review by ezr-ondrej — APPROVED** [review]
apart of missing description, looks great to me :+1:

**Comment by ezr-ondrej** [comment]
btw did you mean to send it for frontend as well? :)

**Comment by akhil-jha** [comment]
> btw did you mean to send it for frontend as well? :)

I will :)

**Pull request merged**
