### PR TITLE
Rename InstanceReservation model

### PR DESCRIPTION
**Pull request by lzap**
SSIA

We use plural form for all tables and singular for models. Updated CONTRIBUTING file.

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Agreed, I did not realize in the big PR :(
Thanks @lzap  ! :+1:

**Review by ezr-ondrej — CHANGES_REQUESTED** [review]
We are using the table in DAO sql statements, we will need to update it there as well (good catch DAO tests!)
Could you please? :)

**Comment by lzap** [comment]
> We are using the table in DAO sql statements, we will need to update it there as well (good catch DAO tests!)

I missed the reset_sequences() utility function I think, rebased. Or else I don't see what is causing the tests to fail.

**Comment by adiabramovitch** [comment]
```
--- FAIL: TestDeleteReservation (0.29s)
    reservation_test.go:55: Delete reservation test failed: DAO error: sqlx reservation prepare statement error: INSERT INTO instance_reservation (reservation_id, instance_id) VALUES ($1, $2): ERROR: relation "instance_reservation" does not exist (SQLSTATE 42P01): ERROR: relation "instance_reservation" does not exist (SQLSTATE 42P01)
```

**Comment by lzap** [comment]
Oh DAO SQL statements! If course, thanks, rebased.

**Comment by lzap** [comment]
Green.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @lzap ! :+1:

**Pull request merged**
