### PR TITLE
feat: Add Azure reservation to OpenAPI

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Add OpenAPI endpoint for Azure reservation.

Fixes HMS-1182

### CODE REVIEW

**Review by lzap — APPROVED** [review]
TY

**Comment by lzap** [comment]
Enabled auto merge, @akhil-jha since you asked... :-)

**Comment by ezr-ondrej** [comment]
> Enabled auto merge, @akhil-jha since you asked... :-)

I believe we want to wait with merging this until we have the IQE automation ready ;)

**Review by akhil-jha — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
Rebased on top of main, no change.

**Comment by ezr-ondrej** [comment]
Aaaand merged :tada: Thanks @akhil-jha for making sure it works! :+1:

**Pull request merged**
