### PR TITLE
refactor: Regenerate HTTP clients

### PR DESCRIPTION
**Pull request by adiabramovitch**
In order to enable source filtering by provider type, I wanted to check if sources have fixed their filtering bug. 
In order to do that, I need to regenerate sources' client. 
We need to regenerate the clients as they had a few changes, I have fixed IB conflicts. 
Moreover, the ID type definition was duplicated therefore I added ID to the excluded schemas and checked the launch instance workflow works, as usual, to make sure the change didn't break anything. 
also, I have removed the compatibility section because it was not needed. 

If you can, please check this as well before merging.

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
nice! Thanks @adiabramovitch ! :orange_heart:
Did sources fixed the filter issue? :)

**Comment by adiabramovitch** [comment]
> nice! Thanks @adiabramovitch ! orange_heart Did sources fixed the filter issue? :)

Doesnt seems so, for now, we will fetch all of  provisioning sources and filter by provider type on our side

**Comment by ezr-ondrej** [comment]
> Doesnt seems so, for now, we will fetch all of provisioning sources and filter by provider type on our side

That's a bummer, but at least we've updated the clients :)

**Comment by lzap** [comment]
> In order to do that, I need to regenerate sources' client.

GENIUS :-)

**Pull request merged**
