### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by lzap**
Hopefully resolves https://github.com/advisories/GHSA-rcjv-mgp8-qvmr

Had to pin two dependencies because of 1.19 incompatibility already.

### CODE REVIEW

**Comment by lzap** [comment]
Will fix:

```
internal/telemetry/otel.go:13:2: SA1019: "go.opentelemetry.io/otel/exporters/jaeger" is deprecated: This module is no longer supported. OpenTelemetry dropped support for Jaeger exporter in July 2023. Jaeger officially accepts and recommends using OTLP. Use [go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp] or [go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc] instead. (staticcheck)
```

**Comment by lzap** [comment]
Part of this PR is a small refactoring of tracing - we had to move from deprecated Jaeger exporter to OTLP exporter. With that, a small improvement - all errors of the tracing library now go into our Zerolog (thus platform logs). This works great, tested. However, I do not have Jaeger installed anymore, can you test it actually works @ezr-ondrej please?

**Comment by lzap** [comment]
Fixing Jaeger deprecation in another PR, then I will rebase this one on top of that.

**Comment by ezr-ondrej** [comment]
Is this ready for rebase? :)

**Comment by lzap** [comment]
Rebased.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @lzap ! :+1:

**Pull request merged**
