### PR TITLE
fix(HMS-1107): update permissions to match sources

### PR DESCRIPTION
**Pull request by lzap**
For a new feature, we need to be able to create and list Launch Templates on EC2. This adds those permissions. We would like this to get merged earlier before we go into production beta so there is no second version of sources in prod.

This patch synces the docs against sources after this patch is merged: https://github.com/RedHatInsights/sources-api-go/pull/636

### CODE REVIEW

**Review by adiabramovitch — DISMISSED** [review]

**Comment by lzap** [comment]
Since we are touching this, I suggest to add few more permissions to be able to check in the future if the policy is not outdated. That would be:

* GetPolicyVersion
* GetPolicy
* ListAttachedRolePolicies

Here is now to do this with AWS CLI: (example for our ITAWS account arn:aws:iam::399XXX895069:role/satellite-services-role). First, list attached policies:

```
$ aws --profile saml iam list-attached-role-policies --role-name satellite-services-role 
{
    "AttachedPolicies": [
        {
            "PolicyName": "satellite-runinstances-policy",
            "PolicyArn": "arn:aws:iam::399XXX895069:policy/satellite-runinstances-policy"
        }
    ]
}
```

Then you need to find the latest version:

```
$ aws --profile saml iam get-policy --policy-arn arn:aws:iam::399XXX895069:policy/satellite-runinstances-policy
{
    "Policy": {
        "PolicyName": "satellite-runinstances-policy",
        "PolicyId": "ANPAV2FE6SKOVYS4GMJVN",
        "Arn": "arn:aws:iam::399XXX895069:policy/satellite-runinstances-policy",
        "Path": "/",
        "DefaultVersionId": "v1",
        "AttachmentCount": 1,
        "PermissionsBoundaryUsageCount": 0,
        "IsAttachable": true,
        "Description": "Policy for role, that allows running instances from ConsoleDot",
        "CreateDate": "2022-09-28T11:50:58Z",
        "UpdateDate": "2022-09-28T11:50:58Z",
        "Tags": [
            {
                "Key": "service",
                "Value": "provisioning"
            },
            {
                "Key": "team",
                "Value": "envision"
            }
        ]
    }
}
```

And finally to fetch the JSON content:

```
$ aws --profile saml iam get-policy-version --policy-arn arn:aws:iam::399XXX895069:policy/satellite-runinstances-policy --version-id v1
{
    "PolicyVersion": {
        "Document": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "RedHatProvisioning",
                    "Effect": "Allow",
                    "Action": [
                        "ec2:CreateKeyPair",
                        "ec2:CreateTags",
                        "ec2:DeleteKeyPair",
                        "ec2:DeleteTags",
                        "ec2:DescribeAvailabilityZones",
                        "ec2:DescribeImages",
                        "ec2:DescribeInstanceTypes",
                        "ec2:DescribeInstances",
                        "ec2:DescribeKeyPairs",
                        "ec2:DescribeRegions",
                        "ec2:DescribeSecurityGroups",
                        "ec2:DescribeSnapshotAttribute",
                        "ec2:DescribeTags",
                        "ec2:ImportKeyPair",
                        "ec2:RunInstances",
                        "ec2:StartInstances"
                    ],
                    "Resource": "*"
                }
            ]
        },
        "VersionId": "v1",
        "IsDefaultVersion": true,
        "CreateDate": "2022-09-28T11:50:58Z"
    }
}
```

**Comment by ezr-ondrej** [comment]
I'm definitelly up for it, sounds cool to be able to do that ! :orange_heart:

**Comment by lzap** [comment]
Added the four IAM policies for the future checker.

**Review by avitova — APPROVED** [review]
LGTM

**Pull request merged**
